# Use Node.js version 18
providers = ["node"]
[variables]
NODE_VERSION = "18"

[phases.install]
cmds = ["cd storefront && npm install --legacy-peer-deps --force"]

[phases.build]
cmds = ["cd storefront && npm run build"]

[start]
cmd = "cd storefront && npm start"
