nodeLinker: node-modules
enableGlobalCache: false
enableInlineHunks: true
enableNetwork: true
compressionLevel: mixed
enableTelemetry: false
logFilters:
  - code: YN0000
    level: discard
  - code: YN0061
    level: discard
  - code: YN0032
    level: discard
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0066
    level: discard