# Use Node.js version 18
providers = ["node"]
[variables]
NODE_VERSION = "18"

[phases.install]
cmds = ["npm install --legacy-peer-deps --force"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
